name: cicd pipeline for springboot
on:
  push:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chekout the code
        uses: actions/checkout@v4.2.2
      - name: java setup for test appllication
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: setup for postgrepsql
        run: |
          sudo apt install postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          psql -U postgres -P postgres
          ALTER USER username postgres WITH PASSWORD 'postgres';
      
      - name: compile the code before testing
        run: |
          cd springboot-compose
          mvn install compile
        
          
      
      
