name: Continuous Integration for Spring Boot Applications

on:
  push:
    branches: ["main"]

jobs:
  compile-and-build:
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:15.10-alpine3.21
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: employee_db
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: List files at root
        run: ls -al

      - name: List files in springboot-compose
        working-directory: springboot-compose
        run: ls -la

      - name: Compile the code
        working-directory: springboot-compose
        run: mvn install
