name: cicd pipeline for springboot
on:
  push:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chekout the code
        uses: actions/checkout@v4.2.2
      - name: java setup for test appllication
        uses: actions/setup-java@v4
      - name: compile the code before testing
        run: |
          cd springboot-compose
          mvn install
          mvn compile
        
          
      
      
