name: cicd pipeline for springboot
on:
  push:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chekout the code
        uses: actions/checkout@v4.2.2
      - name: to check where its is download
        run: |
          ls
          pwd
